import os
import numpy as np

def import_decks(subfolder_name, base_path="./data/method_1/"):
    """
    function that takes a subfolder name as an argument, where the .npz files 
    for a certain amount of decks with a specific random seed are stored.

    returns a numpy array of numpy arrays, each internal numpy array containing a deck of cards
    with colors represented by the integers '0' and '1'.
    """
    path_to_data = os.path.join(base_path, subfolder_name)

    # ensure folder exists
    if not os.path.isdir(path_to_data):
        raise FileNotFoundError(f"Folder not found: {path_to_data}")

    # making sure all files are .npz files, then ordering them ascending 
    # by the number of decks in cases of multiple files
    files = [f for f in os.listdir(path_to_data) if f.endswith(".npz")]
    files.sort(key=lambda x: int(x.split("_")[1].split("-")[0]))

    decks = []
    # loop through files and load .npz
    for file in files:
        file_path = os.path.join(path_to_data, file)
        print(file_path)
        with np.load(file_path) as opened_file:
            decks.append(opened_file['decks'])

    # combine into one numpy array
    return np.concatenate(decks, axis=0)

def score_a_deck(deck, player1seq, player2seq, to_print = True):
    # should have separate function to read in the particular deck from the file format as generated by method 1 or 2,
    # deck format constant when scoring for now

    num_cards_player1 = 0
    num_cards_player2 = 0
    num_tricks_player1 = 0
    num_tricks_player2 = 0

    ### Scoring logic
    running_sequence = []
    for item in deck:

        running_sequence.append(item)

        if len(running_sequence) > 2: # if the sequence has gotten long enough to be scored

            # slice last 3 item
            if running_sequence[-3:] == player1seq:
                num_tricks_player1 += 1
                num_cards_player1 += len(running_sequence)
                running_sequence = []

            elif running_sequence[-3:] == player2seq:
                num_tricks_player2 += 1
                num_cards_player2 += len(running_sequence)
                running_sequence = []

            # if niether of these are true then the if is exited and another item is appended
    num_cards_left = len(running_sequence) # not sure if we need this value but writing it in incase it is useful later
    ###

    # debugging print statements
    if to_print:
      print(num_cards_player2)
      print(num_cards_player1)
      print(num_tricks_player2)
      print(num_tricks_player1)


    p2_win_card = 0
    draw_card=0
    p2_win_trick=0
    draw_trick=0

    if num_cards_player2 > num_cards_player1:
        p2_win_card += 1 # Doing += because I was having issues with defining variable wrong name at first so this will ensure it is checked to actually exist
    elif num_cards_player2 == num_cards_player1:
        draw_card += 1

    if num_tricks_player2 > num_tricks_player1:
        p2_win_trick += 1
    elif num_tricks_player2 == num_tricks_player1:
        draw_trick += 1

    return_dict = {'p2_win_card':p2_win_card, 'draw_card':draw_card, 'p2_win_trick':p2_win_trick, 'draw_trick':draw_trick}


    return return_dict

def score_a_deck_pointers(deck, player1seq, player2seq, to_print = True):
    # should have separate function to read in the particular deck from the file format as generated by method 1 or 2,
    # deck format constant when scoring for now

    num_cards_player1 = 0
    num_cards_player2 = 0
    num_tricks_player1 = 0
    num_tricks_player2 = 0

    ### Scoring logic
    left_pointer = 0
    right_pointer = 1
    
    for item in deck:

        len_sequence = right_pointer-left_pointer

        if len_sequence > 2: # if the sequence has gotten long enough to be scored
            # slice last 3 item
            if (deck[right_pointer-3] == player1seq[0] and
            deck[right_pointer-2] == player1seq[1] and
            deck[right_pointer-1] == player1seq[2]):
                num_tricks_player1 += 1
                num_cards_player1 += len_sequence
                left_pointer = right_pointer

            elif (deck[right_pointer-3] == player2seq[0] and
            deck[right_pointer-2] == player2seq[1] and
            deck[right_pointer-1] == player2seq[2]):
                num_tricks_player2 += 1
                num_cards_player2 += len_sequence
                left_pointer = right_pointer
                
        right_pointer += 1
                

    #         # if niether of these are true then the if is exited and another item is appended
    # num_cards_left = len(running_sequence) # not sure if we need this value but writing it in incase it is useful later
    # ###

    # debugging print statements
    if to_print:
      print(num_cards_player2)
      print(num_cards_player1)
      print(num_tricks_player2)
      print(num_tricks_player1)


    p2_win_card = 0
    draw_card=0
    p2_win_trick=0
    draw_trick=0

    if num_cards_player2 > num_cards_player1:
        p2_win_card += 1 # Doing += because I was having issues with defining variable wrong name at first so this will ensure it is checked to actually exist
    elif num_cards_player2 == num_cards_player1:
        draw_card += 1

    if num_tricks_player2 > num_tricks_player1:
        p2_win_trick += 1
    elif num_tricks_player2 == num_tricks_player1:
        draw_trick += 1

    return_dict = {'p2_win_card':p2_win_card, 'draw_card':draw_card, 'p2_win_trick':p2_win_trick, 'draw_trick':draw_trick}


    return return_dict