import os
import numpy as np
import itertools
import pandas as pd
from collections import defaultdict

def import_decks(subfolder_name, base_path="./data/method_1/"):
    """
    function that takes a subfolder name as an argument, where the .npz files 
    for a certain amount of decks with a specific random seed are stored.

    returns a numpy array of numpy arrays, each internal numpy array containing a deck of cards
    with colors represented by the integers '0' and '1'.
    """
    path_to_data = os.path.join(base_path, subfolder_name)

    # ensure folder exists
    if not os.path.isdir(path_to_data):
        raise FileNotFoundError(f"Folder not found: {path_to_data}")

    # making sure all files are .npz files, then ordering them ascending 
    # by the number of decks in cases of multiple files
    files = [f for f in os.listdir(path_to_data) if f.endswith(".npz")]
    files.sort(key=lambda x: int(x.split("_")[1].split("-")[0]))

    decks = []
    # loop through files and load .npz
    for file in files:
        file_path = os.path.join(path_to_data, file)
        print(f'importing decks from {file_path}...')
        with np.load(file_path) as opened_file:
            decks.append(opened_file['decks'])

    # combine into one numpy array
    main_array = np.concatenate(decks, axis=0)
    print('All decks successfully imported!')
    return main_array

def score_a_deck(deck, player1seq, player2seq, to_print = True):
    # should have separate function to read in the particular deck from the file format as generated by method 1 or 2,
    # deck format constant when scoring for now

    num_cards_player1 = 0
    num_cards_player2 = 0
    num_tricks_player1 = 0
    num_tricks_player2 = 0

    ### Scoring logic
    running_sequence = []
    for item in deck:

        running_sequence.append(item)

        if len(running_sequence) > 2: # if the sequence has gotten long enough to be scored

            # slice last 3 item
            if running_sequence[-3:] == player1seq:
                num_tricks_player1 += 1
                num_cards_player1 += len(running_sequence)
                running_sequence = []

            elif running_sequence[-3:] == player2seq:
                num_tricks_player2 += 1
                num_cards_player2 += len(running_sequence)
                running_sequence = []

            # if niether of these are true then the if is exited and another item is appended
    num_cards_left = len(running_sequence) # not sure if we need this value but writing it in incase it is useful later
    ###

    # debugging print statements
    if to_print:
      print(num_cards_player2)
      print(num_cards_player1)
      print(num_tricks_player2)
      print(num_tricks_player1)

    p1_win_card = 0
    p2_win_card = 0
    draw_card=0
    p1_win_trick = 0
    p2_win_trick=0
    draw_trick=0

    if num_cards_player2 > num_cards_player1:
      p2_win_card += 1 # Doing += because I was having issues with defining variable wrong name at first so this will ensure it is checked to actually exist
    elif num_cards_player1 > num_cards_player2:
      p1_win_card += 1
    else:
        draw_card += 1

    if num_tricks_player2 > num_tricks_player1:
      p2_win_trick += 1
    elif num_tricks_player1 > num_tricks_player2:
      p1_win_trick += 1
    else:
      draw_trick += 1


    return_dict = {'p1_win_cards':p1_win_card, 
                   'p2_win_cards':p2_win_card, 
                   'draw_cards':draw_card, 
                   'p1_win_tricks':p1_win_trick,
                   'p2_win_tricks':p2_win_trick, 
                   'draw_tricks':draw_trick}


    return return_dict

def score_a_deck_pointers(deck, player1seq, player2seq, to_print = True):
    # should have separate function to read in the particular deck from the file format as generated by method 1 or 2,
    # deck format constant when scoring for now

    num_cards_player1 = 0
    num_cards_player2 = 0
    num_tricks_player1 = 0
    num_tricks_player2 = 0

    ### Scoring logic
    left_pointer = 0
    right_pointer = 1
    
    for item in deck:

        len_sequence = right_pointer-left_pointer

        if len_sequence > 2: # if the sequence has gotten long enough to be scored
            # slice last 3 item
            if (deck[right_pointer-3] == player1seq[0] and
            deck[right_pointer-2] == player1seq[1] and
            deck[right_pointer-1] == player1seq[2]):
                num_tricks_player1 += 1
                num_cards_player1 += len_sequence
                left_pointer = right_pointer

            elif (deck[right_pointer-3] == player2seq[0] and
            deck[right_pointer-2] == player2seq[1] and
            deck[right_pointer-1] == player2seq[2]):
                num_tricks_player2 += 1
                num_cards_player2 += len_sequence
                left_pointer = right_pointer
                
        right_pointer += 1
                

    #         # if niether of these are true then the if is exited and another item is appended
    # num_cards_left = len(running_sequence) # not sure if we need this value but writing it in incase it is useful later
    # ###

    # debugging print statements
    if to_print:
      print(num_cards_player2)
      print(num_cards_player1)
      print(num_tricks_player2)
      print(num_tricks_player1)


    p2_win_card = 0
    draw_card=0
    p2_win_trick=0
    draw_trick=0

    if num_cards_player2 > num_cards_player1:
        p2_win_card += 1 # Doing += because I was having issues with defining variable wrong name at first so this will ensure it is checked to actually exist
    elif num_cards_player2 == num_cards_player1:
        draw_card += 1

    if num_tricks_player2 > num_tricks_player1:
        p2_win_trick += 1
    elif num_tricks_player2 == num_tricks_player1:
        draw_trick += 1

    return_dict = {'p2_win_cards':p2_win_card, 'draw_cards':draw_card, 'p2_win_tricks':p2_win_trick, 'draw_tricks':draw_trick}


    return return_dict


def bits_to_string(bits):
    """
    Because our generated decks are stored as arrays of 0s and 1s, 
    we want to convert the 0s into 'B' and the 1s into 'R'
    for the human reader to understand that we are playing with cards :)
    """
    mapping = {0: "B", 1: "R"}
    return "".join(mapping[b] for b in bits)

def batch_score_all_combos(decks):
  """
  Function that scores an array of decks of cards based on p1 and p2 wins (and draws), 
  both in terms of cards and in terms of tricks, on all 56 valid combinations of games.
  Returns a pandas dataframe of the results.
  """
  print('Beginning to score all 56 combinations of card games on the data...')
  # generating all possible game combinations (there are 8 of them)
  lists_3 = [list(x) for x in itertools.product([0, 1], repeat=3)]

  # making a list of tuples, each tuple containing 2 card selection lists (excluding games that are identical) (there are 56 of them)
  pairs = [(a, b) for a in lists_3 for b in lists_3 if a != b]

  all_games = [] # list that eventually stores all 56 game results

  for card_combo in pairs: # looping through every valid game combination

    one_game_sums = defaultdict(int) # defining a dict for the single game being played and scored in this loop iteration

    # putting some information about the specific game being played into that dictionary
    one_game_sums['p1choice'] = bits_to_string(card_combo[0])
    one_game_sums['p2choice'] = bits_to_string(card_combo[1])
    one_game_sums['times_run'] = len(decks)

    #looping through and summing the statistics for each game.
    for deck in decks:
        deck_score = score_a_deck(deck, card_combo[0], card_combo[1], to_print = False)
        for key, value in deck_score.items():
          one_game_sums[key] += value

    all_games.append(one_game_sums)
    #print(f'Done scoring game p1: {card_combo[0]} p2: {card_combo[1]}')

  return pd.DataFrame(all_games)